### ISSUE TITLE
DepCtrl

### ISSUE THREAD

**Issue by garret1317** [garret1317/aegisub-scripts#2]
Would probably be a good idea
but
- do people other than me actually use these
- is it worth the extra friction

**Comment by garret1317** [comment]
need all scripts to have semver
will probably use this as an excuse to update them

**Comment by garret1317** [comment]
some progress in depctrl branch
todo: feed

**Comment by garret1317** [comment]
vast majority of scripts have depctrl support now (and have had for a while)
massive progress on feedmaker, have a completely working feed now!
won't share/add to scripts just yet though, want to iron out the kinks first (and ideally document it)

**Comment by Akatmks** [comment]
Hey! I was looking at the DependencyControl Global Config script and I thought ... oh this script is made specifically for DepCtrl and it doesn't support DepCtrl?! ... and then I find this GitHub Issue. I saw you removed the _help wanted_ tag but do you still need any help to get a DepCtrl generator to work? <3

**Comment by garret1317** [comment]
> I was looking at the DependencyControl Global Config script and I thought ... oh this script is made specifically for DepCtrl and it doesn't support DepCtrl?!

no, it does
most of my scripts check for depctrl and use it if it's available, otherwise they use regular aegisub.register_macro. depctrl config doesn't bother trying without depctrl, because why

as [^above](#issuecomment-1331374355), i have a fully working feed now, not sharing yet for ??? reasons and/or havent got round to it yet

but anyway, you can run the script with depctrl, it works (and it doesnt work without it)
and in theory you can grab it from depctrl as well (but in practice you dont have the feed)

> do you still need any help to get a DepCtrl generator to work? <3

feedmaker is https://github.com/garret1317/depctrl-feedmaker, i've got it working decently enough for my needs (though it breaks in various fun ways on other repos lol)

**Comment by Akatmks** [comment]
![](https://camo.githubusercontent.com/6a0d9327ad42b9a35c302bb9004aa9a9eb27a3f926c82297c7810d4b82845cfe/68747470733a2f2f696d67732e786b63642e636f6d2f636f6d6963732f6175746f6d6174696f6e2e706e67)
Oh I love this from the README of your depctrl-feedmaker!

**Comment by Akatmks** [comment]
Btw I forgot. It's you last time who told me I could directly run the code and provide a fake DepCtrl that get the information for DependencyControl.json!
