### ISSUE TITLE
Dupe and Comment undo should delete the original lines

### ISSUE THREAD

**Issue by Zahuczky** [garret1317/aegisub-scripts#4]
Would be more intuitive, and also much more useful, if "Undo" would remove the commented, original lines. Without deleting other comments between them. Maybe even adding an option to delete the commented lines, and append the original as a comment in { } brackets at the end of the edited line. So the original is visible all the time during editing, but even after deleting them, saving them somewhere from where they can be checked again if needed.

**Comment by garret1317** [comment]
> Would be more intuitive, and also much more useful, if "Undo" would remove the commented, original lines.

Undo = go back to the original, removing the original would defeat the entire point.

> Maybe even adding an option to delete the commented lines, and append the original as a comment in { } brackets at the end of the edited line.

I like seeing the old lines in the grid, it's easier to see what changed than putting a comment on the end, so probably won't do that.
I do like the idea of something to hide the originals though, perhaps storing them in the extradata? (~~todo: how do i do that?~~ [like this](https://gist.github.com/garret1317/420a54a11c1306764be62413b7023d05))

~~Will probably need something to tell apart the originals from just comments, which i currently don't have (too clever). will have a think~~
had a think, nah that's dumb. assume comment below edit = original, that's what the rest of the script does

**Comment by Zahuczky** [comment]
> I like seeing the old lines in the grid

I also like having them as a separate line, *during* editing.
But after editing it's very bad to have all of them in. I mean, after you're done, but still want to preserve them somewhere. That somewhere can be in brackets.

**Comment by garret1317** [comment]
[conversation ensues](https://cdn.discordapp.com/attachments/731874004612153385/958048921131810826/zahu-dupe-and-comment.log.html)

**Comment by garret1317** [comment]
33ff59e it works
todo: compression of/put less stuff in extradata?

**Comment by garret1317** [comment]
https://github.com/arch1t3cht/Aegisub-Scripts/#rewriting-tools seems like what you actually want
somewhere to preserve the comments after you're done is what git is for imo
hiding them in extradata or whatever is invisible bloat
